services:
  - type: web
    name: violencesense-api
    env: node
    region: oregon
    plan: free
    buildCommand: rm -rf node_modules && npm install && npm run build
    startCommand: node dist/server.js
    healthCheckPath: /api/v1/health
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 5000
      - key: MONGODB_URI
        sync: false
      - key: MONGODB_DB_NAME
        value: violencesense
      - key: ML_SERVICE_URL
        sync: false
      - key: DEFAULT_MODEL_PATH
        value: ./models/violence_model_legacy.h5
      - key: MODEL_ARCHITECTURE
        value: keras-cnn
      - key: CORS_ORIGIN
        value: https://violence-sense.vercel.app
